from typing import Protocol

from app.session.models import SessionRequest, SessionSnapshot


class SessionManager(Protocol):
    def create(self, request: SessionRequest) -> SessionSnapshot: ...
    def activate(self) -> SessionSnapshot: ...
    def invalidate(self) -> SessionSnapshot: ...
    def replace(self, request: SessionRequest) -> SessionSnapshot: ...
    def state(self) -> SessionSnapshot: ...
