from enum import StrEnum
class GatewayOutcome(StrEnum):SUCCESS="SUCCESS";FAILED="FAILED"
class NormalizedOrderStatus(StrEnum):PENDING="PENDING";SUBMITTED="SUBMITTED";PARTIALLY_FILLED="PARTIALLY_FILLED";FILLED="FILLED";CANCELLED="CANCELLED";REJECTED="REJECTED";EXPIRED="EXPIRED";UNKNOWN="UNKNOWN"
