from typing import Protocol
from app.webull_gateway.models import *
class WebullGateway(Protocol):
 def authenticate(self,request:LoginRequest)->LoginResponse:...
 def logout(self,request:LogoutRequest)->LogoutResponse:...
 def get_account(self,request:AccountRequest)->AccountResponse:...
 def submit_order(self,request:SubmitOrderRequest)->SubmitOrderResponse:...
 def cancel_order(self,request:CancelOrderRequest)->CancelOrderResponse:...
 def get_order_status(self,request:OrderStatusRequest)->OrderStatusResponse:...
