class SessionBootstrapError(ValueError): pass
class SessionBootstrapDependencyError(SessionBootstrapError): pass
class SessionBootstrapValidationError(SessionBootstrapError): pass
class SessionBootstrapCredentialError(SessionBootstrapError): pass
