from enum import StrEnum
class BrokerOrderType(StrEnum):LIMIT="LIMIT";MARKET="MARKET"
class BrokerTimeInForce(StrEnum):DAY="DAY";GTC="GTC"
class BrokerOrderSide(StrEnum):BUY="BUY";SELL="SELL"
class BrokerTransportStatus(StrEnum):ACCEPTED="ACCEPTED";REJECTED="REJECTED";FAILED="FAILED";UNKNOWN="UNKNOWN"
class BrokerExecutionStatus(StrEnum):SUBMITTED="SUBMITTED";REJECTED="REJECTED";TRANSPORT_FAILED="TRANSPORT_FAILED";BLOCKED="BLOCKED";UNKNOWN="UNKNOWN"
class BrokerExecutionReason(StrEnum):
 SUBMITTED="SUBMITTED";ADAPTER_DISABLED="ADAPTER_DISABLED";INVOCATION_NOT_READY="INVOCATION_NOT_READY";INVOCATION_NOT_LIVE="INVOCATION_NOT_LIVE";INVALID_SYMBOL="INVALID_SYMBOL";INVALID_QUANTITY="INVALID_QUANTITY";INVALID_LIMIT_PRICE="INVALID_LIMIT_PRICE";ORDER_TYPE_NOT_ALLOWED="ORDER_TYPE_NOT_ALLOWED";TIME_IN_FORCE_NOT_ALLOWED="TIME_IN_FORCE_NOT_ALLOWED";QUANTITY_EXCEEDS_LIMIT="QUANTITY_EXCEEDS_LIMIT";NOTIONAL_EXCEEDS_LIMIT="NOTIONAL_EXCEEDS_LIMIT";DUPLICATE_CLIENT_ORDER_ID="DUPLICATE_CLIENT_ORDER_ID";TRANSPORT_REJECTED="TRANSPORT_REJECTED";TRANSPORT_FAILURE="TRANSPORT_FAILURE";RESPONSE_CLIENT_ORDER_ID_MISMATCH="RESPONSE_CLIENT_ORDER_ID_MISMATCH";RESPONSE_QUANTITY_INVALID="RESPONSE_QUANTITY_INVALID";RESPONSE_TIMESTAMP_INVALID="RESPONSE_TIMESTAMP_INVALID";UNKNOWN_TRANSPORT_STATUS="UNKNOWN_TRANSPORT_STATUS"
