from typing import Protocol
class ExecutionJournalPort(Protocol):
    def append_authorization(self,authorization):...
    def append_execution(self,execution):...
    def contains_authorization_id(self,authorization_id):...
    def contains_execution_id(self,execution_id):...
    def load_authorization_ids(self):...
    def load_execution_ids(self):...
    def load_records(self):...
    def verify_integrity(self):...
