from typing import Protocol
from app.transport_runtime.models import TransportExecutionRecord,TransportRequest,TransportResponse
class TransportExecutor(Protocol):
 def execute(self,request:TransportRequest)->TransportResponse:...
class TransportTelemetryHook(Protocol):
 def record(self,record:TransportExecutionRecord)->None:...
class TransportRateLimitHook(Protocol):
 def allow(self,request:TransportRequest)->bool:...
