class WebullAuthenticationApprovalError(ValueError): pass
class WebullAuthenticationApprovalDisabledError(WebullAuthenticationApprovalError): pass
class WebullAuthenticationApprovalDependencyError(WebullAuthenticationApprovalError): pass
class WebullAuthenticationApprovalValidationError(WebullAuthenticationApprovalError): pass
class WebullAuthenticationApprovalBindingError(WebullAuthenticationApprovalError): pass
class WebullAuthenticationApprovalAssessmentError(WebullAuthenticationApprovalError): pass
class WebullAuthenticationApprovalConflictError(WebullAuthenticationApprovalError): pass
