from enum import StrEnum
class WebullOrderAction(StrEnum):BUY="BUY";SELL="SELL"
class WebullOrderType(StrEnum):LMT="LMT";MKT="MKT"
class WebullTimeInForce(StrEnum):DAY="DAY";GTC="GTC"
class WebullGatewayStatus(StrEnum):ACCEPTED="ACCEPTED";REJECTED="REJECTED";FAILED="FAILED";UNKNOWN="UNKNOWN"
class WebullRejectionCode(StrEnum):
 TRANSPORT_DISABLED="WEBULL_TRANSPORT_DISABLED";ENVIRONMENT_MISMATCH="WEBULL_ENVIRONMENT_MISMATCH";SYMBOL_NOT_ALLOWED="WEBULL_SYMBOL_NOT_ALLOWED";INVALID_QUANTITY="WEBULL_INVALID_QUANTITY";ORDER_TYPE_NOT_ALLOWED="WEBULL_ORDER_TYPE_NOT_ALLOWED";TIME_IN_FORCE_NOT_ALLOWED="WEBULL_TIME_IN_FORCE_NOT_ALLOWED";INVALID_LIMIT_PRICE="WEBULL_INVALID_LIMIT_PRICE";QUANTITY_EXCEEDS_LIMIT="WEBULL_QUANTITY_EXCEEDS_LIMIT";NOTIONAL_EXCEEDS_LIMIT="WEBULL_NOTIONAL_EXCEEDS_LIMIT";DUPLICATE_TRANSPORT_REQUEST="WEBULL_DUPLICATE_TRANSPORT_REQUEST";GATEWAY_FAILURE="WEBULL_GATEWAY_FAILURE";RESPONSE_REQUEST_ID_MISMATCH="WEBULL_RESPONSE_REQUEST_ID_MISMATCH";RESPONSE_CLIENT_ID_MISMATCH="WEBULL_RESPONSE_CLIENT_ID_MISMATCH";RESPONSE_QUANTITY_INVALID="WEBULL_RESPONSE_QUANTITY_INVALID";RESPONSE_TIMESTAMP_INVALID="WEBULL_RESPONSE_TIMESTAMP_INVALID";UNKNOWN_STATUS="WEBULL_UNKNOWN_STATUS"
