from typing import Protocol
from app.historical_replay import HistoricalReplayRequest,HistoricalReplayResult
from app.replay_cycle_projection import ReplayCycleProjectionRequest,ReplayCycleProjectionResult
from app.trade_journal_batch import TradeJournalBatchRequest,TradeJournalBatchResult
from app.analytics import AnalyticsRequest,AnalyticsResult
class HistoricalReplayRunner(Protocol):
    def replay(self,request:HistoricalReplayRequest)->HistoricalReplayResult:...
class ReplayCycleProjectionRunner(Protocol):
    def project(self,request:ReplayCycleProjectionRequest)->ReplayCycleProjectionResult:...
class TradeJournalBatchRunner(Protocol):
    def run(self,request:TradeJournalBatchRequest)->TradeJournalBatchResult:...
class AnalyticsRunner(Protocol):
    def evaluate(self,request:AnalyticsRequest)->AnalyticsResult:...
class ProjectionRequestFactory(Protocol):
    def create(self,request,replay_result:HistoricalReplayResult)->ReplayCycleProjectionRequest:...
class JournalBatchRequestFactory(Protocol):
    def create(self,request,projection_result:ReplayCycleProjectionResult)->TradeJournalBatchRequest:...
class AnalyticsRequestFactory(Protocol):
    def create(self,request,journal_result:TradeJournalBatchResult)->AnalyticsRequest:...
