class WebullAuthenticationConfigurationError(ValueError): pass
class WebullAuthenticationConfigurationDependencyError(WebullAuthenticationConfigurationError): pass
class WebullAuthenticationConfigurationValidationError(WebullAuthenticationConfigurationError): pass
class WebullAuthenticationConfigurationFieldError(WebullAuthenticationConfigurationError): pass
class WebullAuthenticationConfigurationProfileError(WebullAuthenticationConfigurationError): pass
class WebullAuthenticationConfigurationPolicyError(WebullAuthenticationConfigurationError): pass
